# Práctica Clase 3

## Numpy

In [3]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [4]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [5]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [6]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
arreglo = arreglo + 1

NameError: name 'arreglo' is not defined

In [ ]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [ ]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [ ]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [ ]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [ ]:
arreglo.shape

(6,)

In [ ]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [ ]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [ ]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [ ]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [ ]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [ ]:
a3 = a1 * a2
a3.shape

(2, 4)

In [ ]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [4]:
import numpy as np

arr = np.arange(0,10,dtype=int)
print(arr)

arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr3 = np.linspace(0,9,100)
np.set_printoptions(2) #especifica los decimales para imprimir en 2 

print(arr3)
#arr3.shape #da la forma de la matrix
arr3.size

[0.   0.09 0.18 0.27 0.36 0.45 0.55 0.64 0.73 0.82 0.91 1.   1.09 1.18
 1.27 1.36 1.45 1.55 1.64 1.73 1.82 1.91 2.   2.09 2.18 2.27 2.36 2.45
 2.55 2.64 2.73 2.82 2.91 3.   3.09 3.18 3.27 3.36 3.45 3.55 3.64 3.73
 3.82 3.91 4.   4.09 4.18 4.27 4.36 4.45 4.55 4.64 4.73 4.82 4.91 5.
 5.09 5.18 5.27 5.36 5.45 5.55 5.64 5.73 5.82 5.91 6.   6.09 6.18 6.27
 6.36 6.45 6.55 6.64 6.73 6.82 6.91 7.   7.09 7.18 7.27 7.36 7.45 7.55
 7.64 7.73 7.82 7.91 8.   8.09 8.18 8.27 8.36 8.45 8.55 8.64 8.73 8.82
 8.91 9.  ]


100

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [17]:
a = np.arange(10,101)
print(a)
maskdivisibles = a[a % 3 == 0] #se lleva solo los divisibles x 3! . 
maskdivisibles

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
#tambien se pueden colocar mascaras sobre las mascaras
maskdivisibles = a[(a % 3 == 0) & (a > 33)]
 #se lleva solo los divisibles x 3! & los que ademas cuplen con (n>33) 
# a[mascara] =  a la mascara de a [aplicale las condiciones...]
maskdivisibles 

array([36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84,
       87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [24]:
matrixceros = np.zeros((5,10), dtype=float) #parentesis rosas le paso la tupla(filas,columnas)
matrixceros



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
matrixceros[(1,3), :] =1
print(matrixceros)


[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


In [38]:
matrixceros[:, (2,7)] = 2
print(matrixceros)


[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [ ]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[137.12277219, 187.22289567, 153.95764007],
        [175.21869487, 188.10311988, 118.02508687]],

       [[157.58773537, 166.74585121, 134.96866874],
        [128.3807111 , 188.91447629, 150.68622952]],

       [[168.77296873, 117.90287547, 115.19825164],
        [123.86197814, 172.33144425, 165.7329653 ]],

       [[157.35784374, 121.82035838, 100.01848734],
        [195.39977874, 188.95736542, 121.54200787]]])

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [ ]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [ ]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [ ]:
a.sum()

519

In [ ]:
a.std()

23.924904214367643

In [ ]:
a.sort(axis=1)

In [ ]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [ ]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [ ]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [ ]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [ ]:
a = np.array([l])

In [ ]:
a.shape

(1, 4, 6)

In [ ]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [ ]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [ ]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
c = a * b 
print(c) 

[[91]]


In [ ]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


numpy.arange and Python's built-in list are both used to create sequences of numbers, but they have some key differences:

numpy.arange creates a NumPy array, whereas list creates a Python list. NumPy arrays have several advantages over Python lists, such as better performance for mathematical operations and the ability to have multiple dimensions.
numpy.arange is generally faster than using a list comprehension to create a sequence of numbers because it is implemented in C and can take advantage of vectorization.
numpy.arange can handle larger sequences of numbers than Python's range function, which is limited by the amount of memory available.
The numpy.arange function can specify the data type of the output, whereas a list comprehension can only output numbers in the default Python int or float data types.
numpy.arange allows for non-integer steps, whereas Python's range function only allows for integer steps.
numpy.arange allows you to easily perform mathematical operations on the entire array, whereas with a list you would have to loop through each element and perform the operation individually.
In summary, numpy.arange is a powerful tool for creating numerical arrays, and is especially useful for large arrays and arrays that will be used in mathematical operations. Python's list is more versatile and can be used for a variety of tasks, but is generally less efficient for numerical operations.