The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data.

To use the NumPy module, we need to import it using:

In [1]:
import numpy as np
print(np.__version__)

1.24.1


Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format

A single line of input containing space separated numbers.

Output Format

Print the reverse NumPy array with type float.

Sample Input

1 2 3 4 -8 -10
Sample Output

[-10.  -8.   4.   3.   2.   1.]

# invertir un array

In [2]:
lista= [1, 3, 2, 4, -8, -10]

arr = np.array(lista)
print(arr)

arr = arr[::-1] # lo doy vuelta
arr = [float(x) for x in arr] #cabio las variables de int a float
arr = np.round(arr) #redondeo el arr
print(arr)

[  1   3   2   4  -8 -10]
[-10.  -8.   4.   2.   3.   1.]


### Cambio de web exercises a https://www.machinelearningplus.com/python/101-numpy-exercises-python/

2. How to create a 1D array?
Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [3]:
array_1D = np.arange(0,10,1)
array_1D


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?
Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [4]:
array_3x3_true = np.full((3,3),True, dtype=bool)
array_3x3_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:

#> array([1, 3, 5, 7, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr %2 == 1] # le aplica la mascara [ arr %2 == 1]


array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
newarr = arr[arr %2 == 1] = -1
newarr

-1

### 6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
arr6 = np.arange(10)
arr6

copyedarr6 = (np.copy(arr6))
 
copyedarr6[copyedarr6 %2 == 1] = -1

print(arr6)
print(copyedarr6)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 7. How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])


In [8]:
arr7 = arr6.reshape(2,5)
arr7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 9. How to stack two arrays horizontally?
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [9]:
#Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

print(a)
print(b)
#np.concatenate([a, b], axis=1)

np.hstack([a, b],)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [10]:
#Input:

a = np.array([1,2,3])
#Desired Output:
print(a)
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#([np.repeat(a, 3,axis =0)]) #el .repeat transforma de [1 2 3] a [1 1 1 2 2 2 3 3 3] (np.r_ lo hace clase repeat
# (np.tile(a,3)) #el .tile convierte de [1 2 3] a [1 2 3 1 2 3 1 2 3]

np.r_[np.repeat(a, 3), np.tile(a, 3)]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Resumiendo, np.arange genera una secuencia de números consecutivos en un rango específico mientras que np.array convierte un objeto iterable en una matriz numpy.

### 11. How to get the common items between two python numpy arrays?
Difficulty Level: L2

Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

array([2, 4])

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

#Desired Output:
#array([2, 4])

array([2, 4])

### 12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Desired Output:

array([1,2,3,4])

In [12]:
#Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Desired Output:
#array([1,2,3,4])


np.setdiff1d(a,b) #los que no salen de a en b



array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

#> (array([1, 3, 5, 7]),)

In [13]:

#Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:
#> (array([1, 3, 5, 7]),)


np.where(a == b) # averigua las posiciones en donde los valores se repiten.
#> (array([1, 3, 5, 7]),)


(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
Desired Output:

(array([6, 9, 10]),)

In [14]:
#Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])



# Method 1
#index = np.where((a >= 5) & (a <= 10))
#a[index]

# Method 2:
#index = np.where(np.logical_and(a>=5, a<=10))
#a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]  #le pasas una mascara con esos valores



# Desired Output:
#(array([6, 9, 10]),)

array([ 6,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:


def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [15]:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float]) # toma el valor maximo comparando a b por su indice y toamndo el mayor de ambas.

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [16]:


arr = np.arange(9).reshape(3,3)
print(arr)

print(arr[:, [1,0,2]])

# Imprimir( el array [desde todo:hasta todo, 
# reordenando [1,0,2]]) en lugar de la secuencia logica que trae [0,1,2]

# cambia el orden de presentacion de las columnas rota la 1 con la 0.

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


### 17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [17]:


#Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
print(arr)

arr[[1,0,2],:] # intercambia la fila 0 con la 1 de lugar

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

In [18]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


### 19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

In [19]:

# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[:, ::-1] # arr[desdetodo:hastatodo (en las filas), desdetodo:hastatodo(en las columnas) : segundo axis!(:-1) reveerse order]
#> array([[2, 1, 0],
#>        [5, 4, 3],
#>        [8, 7, 6]])

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [20]:
arr= np.linspace(5,10,15).reshape(5,3) # crea un array del 5 al 10 de 15 paradas, luego le da reshape para acomodar
#la matrix en lugar de (1,15) a (5,3)
#arr = np.around(arr, decimals=3) #redondea a 3 decimales todos los elementos del array


# Limit to 3 decimal places
np.set_printoptions(precision=3)


print(arr)

[[ 5.     5.357  5.714]
 [ 6.071  6.429  6.786]
 [ 7.143  7.5    7.857]
 [ 8.214  8.571  8.929]
 [ 9.286  9.643 10.   ]]


### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Input:

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

In [21]:

#Input:

# Create the random array
# Reset printoptions to default
np.set_printoptions(suppress=False)


rand_arr = np.random.random([3,3])/1e3

# hacer que no muestre como ex?  
np.set_printoptions(suppress= True, precision=6)  # precision is optional y transforma de notacion cient. a
#decimal precision 6
print(rand_arr) 


#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

#Desired Output:

#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

[[0.000186 0.000696 0.000611]
 [0.000287 0.000232 0.000119]
 [0.000852 0.000035 0.000499]]


##### np.random.seed(100) 
sets the seed for the pseudorandom number generator in the numpy random module. A random seed (or seed state, or just seed) is a number (or vector) used to initialize a pseudorandom number generator. When the generator is initialized with the same seed, it will produce the same sequence of random numbers. This is useful for reproducibility, for example if you want to generate the same random numbers in multiple runs of a program or if you want to compare results with different methods. By setting the seed to a specific value, you can ensure that the random numbers generated in your code will be the same every time you run it.

### 23. How to limit the number of items printed in output of numpy array?
Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Input:

a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
Desired Output:

#> array([ 0,  1,  2, ..., 12, 13, 14])

In [22]:
#Input:

a = np.arange(15)
np.set_printoptions(threshold=6)

a
#> array([ 0,  1,  2, ..., 12, 13, 14])
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#Desired Output:

#> array([ 0,  1,  2, ..., 12, 13, 14])

array([ 0,  1,  2, ..., 12, 13, 14])

### 24. How to print the full numpy array without truncating
Difficulty Level: L1

Q. Print the full numpy array a without truncating.

Input:

np.set_printoptions(threshold=6)
a = np.arange(15)
a
#> array([ 0,  1,  2, ..., 12, 13, 14])
Desired Output:

a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:

np.set_printoptions(threshold=6)
a = np.arange(15)

# Solution
np.set_printoptions(threshold=len(a))
a

#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [24]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object') #importa desde una url
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
#iris[:3]
#or 
import pandas as pd
iris_df = pd.DataFrame(iris,columns=names)
iris_df.head(3)

#> array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

sepallength sepalwidth petallength petalwidth         species
0      b'5.1'     b'3.5'      b'1.4'     b'0.2'  b'Iris-setosa'
1      b'4.9'     b'3.0'      b'1.4'     b'0.2'  b'Iris-setosa'
2      b'4.7'     b'3.2'      b'1.3'     b'0.2'  b'Iris-setosa'

### 27. How to convert a 1d array of tuples to a 2d numpy array?
Difficulty Level: L2

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

In [25]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
# Method 1: Convert each row to a list and get the first 4 items

print(iris_1d)

                #saca col 4 por cada linea en iris_1d
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 columns from source url
#iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#iris_2d[:4]
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])


[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') ...
 (6.5, 3. , 5.2, 2. , b'Iris-virginica')
 (6.2, 3.4, 5.4, 2.3, b'Iris-virginica')
 (5.9, 3. , 5.1, 1.8, b'Iris-virginica')]


C:\Users\Luca\AppData\Local\Temp\ipykernel_32508\1686027281.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

### 28. How to compute the mean, median, standard deviation of a numpy array?
Difficulty: L1

Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)



iris_df = pd.read_csv(url, header=None) #lo lee como CSV
iris = iris_df.values # toma todos los values de iris df y los almacena en una var.
print(iris)
sepallength = iris[:,0]#desde :hasta (filas), desde : hasta (colums).
print(sepallength) 
mean = np.mean(sepallength)
median = np.median(sepallength)
std = np.std(sepallength)

print(mean, median, std)

C:\Users\Luca\AppData\Local\Temp\ipykernel_32508\2850253283.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 ...
 [6.5 3.0 5.2 2.0 'Iris-virginica']
 [6.2 3.4 5.4 2.3 'Iris-virginica']
 [5.9 3.0 5.1 1.8 'Iris-virginica']]
[5.1 4.9 4.7 ... 6.5 6.2 5.9]
5.843333333333335 5.8 0.8253012917851409


### 29. How to normalize an array so the values range exactly between 0 and 1?
Difficulty: L2

Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

Input:

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [28]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print (S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]

[0.222222 0.166667 0.111111 ... 0.611111 0.527778 0.444444]


### 30. How to compute the softmax score?
Difficulty Level: L3

Q. Compute the softmax score of sepallength.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [29]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 ... 0.009001 0.006668 0.00494 ]


### 31. How to find the percentile scores of a numpy array?
Difficulty Level: L1

Q. Find the 5th and 95th percentile of iris's sepallength

In [30]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
np.percentile(sepallength, q=(5,95))
#> array([ 4.6  ,  7.255])

array([4.6  , 7.255])

### 32. How to insert values at random positions in an array?
Difficulty Level: L2

Q. Insert np.nan values at 20 random positions in iris_2d dataset

In [31]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


### 33. How to find the position of missing values in numpy array?
Difficulty Level: L2

Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [32]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))
#> Number of missing values: 
#>  5
#> Position of missing values: 
#>  (array([ 39,  88,  99, 130, 147]),)

Number of missing values: 
 5
Position of missing values: 
 (array([ 38,  80, 106, 113, 121], dtype=int64),)


### 34. How to filter a numpy array based on two or more conditions?
Difficulty Level: L3

Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [33]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]
#> array([[ 4.8,  3.4,  1.6,  0.2],
#>        [ 4.8,  3.4,  1.9,  0.2],
#>        [ 4.7,  3.2,  1.6,  0.2],
#>        [ 4.8,  3.1,  1.6,  0.2],
#>        [ 4.9,  2.4,  3.3,  1. ],
#>        [ 4.9,  2.5,  4.5,  1.7]])

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### 35. How to drop rows that contain a missing value from a numpy array?
Difficulty Level: L3:

Q. Select the rows of iris_2d that does not have any nan value.

In [34]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

# Method 2: (By Rong)
#iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]
#> array([[ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2],
#>        [ 5. ,  3.6,  1.4,  0.2],
#>        [ 5.4,  3.9,  1.7,  0.4]])

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

### 36. How to find the correlation between two columns of a numpy array?
Difficulty Level: L2

Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [36]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]
# Solution 2
#from scipy.stats.stats import pearsonr  
#corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
#print(corr)

# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1.

# The p-value roughly indicates the probability of an uncorrelated system producing 
# datasets that have a correlation at least as extreme as the one computed.
# The lower the p-value (<0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.
#> 0.871754157305


0.8717541573048718

### 37. How to find if a given array has any null values?
Difficulty Level: L2

Q. Find out if iris_2d has any missing values.



In [37]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()
#> False

False

### 38. How to replace all missing values with 0 in a numpy array?
Difficulty Level: L2

Q. Replace all ccurrences of nan with 0 in numpy array

In [39]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:10]
#> array([[ 5.1,  3.5,  1.4,  0. ],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       ...,
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

### 39. How to find the count of unique values in a numpy array?
Difficulty Level: L2

Q. Find the unique values and the count of unique values in iris's species

In [40]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])

# Get the unique values and the counts
np.unique(species, return_counts=True)
#> (array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
#>        dtype='|S15'), array([50, 50, 50]))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

### 56. How to find the maximum value in each row of a numpy array 2d?
DifficultyLevel: L2

Q. Compute the maximum for each row in the given array

In [45]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution 1
np.amax(a, axis=1)

# Solution 2
np.apply_along_axis(np.max, arr=a, axis=1)
#> array([9, 8, 6, 3, 9])

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

### 58. How to find the duplicate records in a numpy array?
Difficulty Level: L3

Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

In [46]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

## Solution
# There is no direct function to do this as of 1.13.3

# Create an all True array
out = np.full(a.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)
#> [False  True False  True False False  True  True  True  True]

[False  True False  True False False  True  True  True  True]


### 59. How to find the grouped mean in numpy?
Difficulty Level L3

Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

Input:

In [49]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

# For Loop version
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output
#> [[b'Iris-setosa', 3.418],
#>  [b'Iris-versicolor', 2.770],
#>  [b'Iris-virginica', 2.974]]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

### 60. How to convert a PIL image to numpy array?
Difficulty Level: L3

Q. Import the image from the following URL and convert it to a numpy array.

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [50]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

ModuleNotFoundError: No module named 'requests'

### 61. How to drop all missing values from a numpy array?
Difficulty Level: L2

Q. Drop all nan values from a 1D numpy array


In [53]:

#Input:

np.array([1,2,3,np.nan,5,6,7,np.nan])

#Desired Output:

#array([ 1.,  2.,  3.,  5.,  6.,  7.])
#Show Solution

a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]
#> array([ 1.,  2.,  3.,  5.,  6.,  7.])

array([1., 2., 3., 5., 6., 7.])

### 62. How to compute the euclidean distance between two arrays?
Difficulty Level: L3

Q. Compute the euclidean distance between two arrays 


In mathematics, the Euclidean distance between two points in Euclidean space is the length of a line segment between the two points.

In [54]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Solution
dist = np.linalg.norm(a-b)
dist
#> 6.7082039324993694

6.708203932499369

### 63. How to find all the local maxima (or peaks) in a 1d array?
Difficulty Level: L4

Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

Desired Output:

#> array([2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.

In [55]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations
#> array([2, 5])

array([2, 5], dtype=int64)